face mask detetction/app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

face mask detetction/app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

face mask detetction/app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera

from source.test_new_images import detect_mask_in_image
from source.video_detector import detect_mask_in_frame


@main_bp.route("/")
def home_page():
    return render_template("home_page.html")


def gen(camera):

    while True:
        frame = camera.get_frame()
        frame_processed = detect_mask_in_frame(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-mask-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = detect_mask_in_image(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img


# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Detect mask')

face mask detetction/app/templates/home_page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Face Mask Detector</title>

  <!-- Favicons -->
  <link href="assets/img/favicon.svg" rel="icon">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  

            <!-- Vendor CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="/static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="/static/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/static/vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
  <link href="/static/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="/static/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="/static/vendor/aos/aos.css" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="/static/style.css" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="/">Face Mask Detector</a></h1>
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#team">Team</a></li>
          <li><a href="#cta">Get Started</a></li>

        </ul>
      </nav>

    </div>
  </header>

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex flex-column justify-content-end align-items-center">
    <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Face Mask Detector WebApp</span></h2>
          <p class="animate__animated fanimate__adeInUp">Know if a person is wearing face mask or not</p>
        
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Follow the covid norms</h2>
          <p class="animate__animated animate__fadeInUp">Know how many people at a place are wearing mask and how many are without mask</p>
        </div>
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>

    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
        <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
      </defs>
      
      <g class="wave3">
        <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
      </g>
    </svg>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="section-title" data-aos="zoom-out">
          <h2>About</h2>
          <p>Face Mask Detector</p>
          <br>
        </div>

        <div class="row content justify-content-center" data-aos="fade-up">
          <div class="col-lg-10">
            <p>
                This project is made with an aim to enforce the mandate for wearing masks in public places following
                Covid19 Norm and to make a working model for accurate mask detection
                by image processing.
                With this web app we want to track percentage of people not wearing face masks and area where less
                mask is detected to restrictions in specific areas only

            </p>
            <P>
              For now we can see the working model of our project where user can turn on their system's web camera and can detect number 
              of faces wearing masks and no of faces not wearing masks.
            </P>
            <br> <br>
            <a href="#cta" class="btn-learn-more">Get Started</a>
          </div>
        </div>
    </section><!-- End About Section -->

    <!-- ======= Cta Section ======= -->
    <section id="cta" class="cta">
      <div class="container">

        <div class="row" data-aos="zoom-out">
          <div class="col-lg-9 text-center text-lg-left">
            <h3>Use the Application</h3>
          </div>
          <div class="col-lg-3 cta-btn-container text-center">
            <button id="start" onclick="start()" class="cta-btn align-middle"><i class="fa fa-video-camera"
                aria-hidden="true"></i> Start
</button>
            <button id="stop" onclick="stop()" class="cta-btn align-middle"><i class="fa fa-stop"
                aria-hidden="true"></i> Stop
          </div>
        </div>

      </div>
    </section><!-- End Cta Section -->
    <div class="row">
      <div class="col-lg-12 text-center">
        <img src="" class="img-fluid text-center" alt="" style="margin-top: 20vh; margin-bottom: 5vh;">
      </div>
    </div>
   
    <section id="next">
      <div class="container-fluid">
        

        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="section-title" data-aos="zoom-out">
              <h1>Whats Next</h1>
              <p></p>
            </div>
            <p class="next">
              We are looking forward to integrate our ml model with cctv cameras which are installed at public places 
              where in percentage of people not weraing mask in a particular area can be detected. We can also integrate it 
              in cameras placed outside shops and malls which have automatic gate opeining entry wherein people without Mask
              are not allowed to enter.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- ======= Team Section ======= -->
    <section id="team" class="team">
      <div class="container">

        <div class="section-title" data-aos="zoom-out">
          <h2>Team</h2>
          <p>Our Team</p>
        </div>

        <div class="row">

          <div class="col-lg-3 col-md-3 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up">
              <div class="member-img">
                
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Aditya Jain</h4>
                <span>Full Stack Web Developer and ML</span>
                <h3>19BIT0050</h3>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-3 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up">
              <div class="member-img">
                
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Sayyam Maske</h4>
                <span>Web Developer</span>
                <h3>19BIT0045</h3>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-3 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Naman Jain</h4>
                <span>ML</span>
                <h3>19BIT0002</h3>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-3 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Keshav Aggraval</h4>
                <span>ML</span>
                <h3>19BIT0009</h3>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>
    <!-- End Team Section -->


  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>Face Mask Detector</h3>
      <p>Detecting face masks, keeping people safe</p>
      <div class="credits">
        Designed by <a href="https://www.linkedin.com/in/aditya-jain-479b96157/">Aditya jain</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="/static/vendor/php-email-form/validate.js"></script>
  <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/vendor/venobox/venobox.min.js"></script>
  <script src="/static/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="/static/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/main.js"></script>

  <script>
    $(document).ready(function(){
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
    })
    
        function stop(){
            $("img").attr("src", "/static/images/stay-safe.jpg");
            $("#stop").attr("class","cta-btn align-middle");
    
            $("#start").attr("class","cta-btn align-middle");
        }
        function start(){
            $("img").attr("src", "{{url_for('main.video_feed')}}");
            $("#start").attr("class","cta-btn align-middle");
    
            $("#stop").attr("class","cta-btn align-middle");
        }
    
    </script>

</body>

</html>

face mask detetction/app/templates/image_detector.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="jumbotron">
        <div class="row">
            <div class="col-12">
                <h1>Try the mask detector on custom images</h1>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="container-fluid">
            <div id="frame_container" class="row">
                <div class="col-12">
                    <img src="/static/images/mask.jpg" id="image-preview" style="max-width:600px"
                         class="img-thumbnail img-fluid mx-auto d-block">
                </div>
            </div>
            <div class="row mt-3 mb-5">
                <div class="col-12 d-flex justify-content-center">
    
                    <form enctype="multipart/form-data" id="image-form" method="POST">
                        <div class="row" id="form-row">
                            <div class="col-12">
                                {{ form.csrf_token() }}
    
                                {{ form.image.label(class="custom-file-label") }}
                                {% if form.image.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.image.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <div class="custom-file">
                                    {{ form.image(class="custom-file-input",
                                    id="new-image", onchange="previewImage(event)") }}
                                </div>
                                {% endif %}
                            </div>
                        </div>
    
                        <div class="row mt-3">
                            <div class="col-12 d-flex justify-content-center">
                                {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <hr>
            <div class="row">
                <h4>What is this?</h4>
            </div>
            <div class="row">
                <p>This is a mask detector, an algorithm based on deep neural networks that detects people in images and
                    write a bounding box around faces, looking if they were masks or not. This is not for security
                    purpose.</p>
                <p>If you are interested in more details, check this post I wrote!</p>
            </div>
            <div class="row">
                <h4>Who I am</h4>
            </div>
            <div class="row mb-5">
                <p>I'm Galileo Parise, data scientist and matematician, and I've developed what you see during Italy's
                    second lockdown in November, in which I had lots of free time. If you are interested in this and ohter
                    stories,
                    you can follow me on Linkedin and on Medium.
                    Hoping to get soon over this situation,
                    I hope you all good health:</p>
                <p class="d-flex mx-auto lead text-danger"><strong>please, stay safe and wear a mask</strong>.</p>
                <p></p>
            </div>
        </div>
    </div>
    
    <script>
    var previewImage = function(event) {
        var element_id = "image-preview";
        var preview = document.getElementById(element_id);
        preview.src = URL.createObjectURL(event.target.files[0]);
        preview.style.display = "block";
        $("#submit").prop("disabled",false);
    };
    $(document).ready(function(){
        $('#live').attr('class', 'nav-item');
        $('#image-detector').attr('class', 'nav-item active');
    })
    $(function() {
            $("#submit").each(function(index){
                $(this).on('click', function(e) {
    
                    var url = "{{ url_for('main.image_processing') }}";
    
                    // Form data
                    var formData = new FormData();
    
                    // Add form data
                $('#image-form').serializeArray().forEach(
                    function(item, index) {
                        formData.append(item.name, item.value);
                    }
                );
                    // Add the files
                    var image = $('#new-image')[0].files[0];
                    formData.append('image', image);
    
                    // AJAX query to the endpoint for deletion
                    $.ajax({
                        type: "POST", // POST HTTP
                        url:  url +'',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function(response) {
    
                            $("#image-preview").attr("src", response);
                            $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                            $("#form-row").remove();
                        },
                        error: function(response){
                            location.reload();
                            // Redirect to this page
                        }
                    });
    
                    return false;
                })
            })
        })
    </script>
    
    
</body>
</html>

face mask detetction/app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Face Mask Detector</title>

  <!-- Favicons -->
  <link href="assets/img/favicon.svg" rel="icon">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
  <link href="vendor/venobox/venobox.css" rel="stylesheet">
  <link href="vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="style.css" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="/">Face Mask Detector</a></h1>
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#team">Team</a></li>
          <li><a href="#cta">Get Started</a></li>

        </ul>
      </nav>

    </div>
  </header>

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex flex-column justify-content-end align-items-center">
    <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Face Mask Detector WebApp</span></h2>
          <p class="animate__animated fanimate__adeInUp">Know if a person is wearing face mask or not</p>
        
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item">
        <div class="carousel-container">
          <h2 class="animate__animated animate__fadeInDown">Follow the covid norms</h2>
          <p class="animate__animated animate__fadeInUp">Know how many people at a place are wearing mask and how many are without mask</p>
        </div>
      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>

    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
      <defs>
        <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
      </defs>
      
      <g class="wave3">
        <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
      </g>
    </svg>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="section-title" data-aos="zoom-out">
          <h2>About</h2>
          <p>Face Mask Detector</p>
          <br>
        </div>

        <div class="row content justify-content-center" data-aos="fade-up">
          <div class="col-lg-10">
            <p>
                This project is made with an aim to enforce the mandate for wearing masks in public places following
                Covid19 Norm and to make a working model for accurate mask detection
                by image processing.
                With this web app we want to track percentage of people not wearing face masks and area where less
                mask is detected to restrictions in specific areas only

            </p>
            <P>
              For now we can see the working model of our project where user can turn on their system's web camera and can detect number 
              of faces wearing masks and no of faces not wearing masks.
            </P>
            <br> <br>
            <a href="#cta" class="btn-learn-more">Get Started</a>
          </div>
        </div>
    </section><!-- End About Section -->

    <!-- ======= Cta Section ======= -->
    <section id="cta" class="cta">
      <div class="container">

        <div class="row" data-aos="zoom-out">
          <div class="col-lg-9 text-center text-lg-left">
            <h3>Use the Application</h3>
          </div>
          <div class="col-lg-3 cta-btn-container text-center">
            <button id="start" onclick="start()" class="cta-btn align-middle"><i class="fa fa-video-camera"
                aria-hidden="true"></i> Start
</button>
            <button id="stop" onclick="stop()" class="cta-btn align-middle"><i class="fa fa-stop"
                aria-hidden="true"></i> Stop
          </div>
        </div>

      </div>
    </section><!-- End Cta Section -->

   
    <section id="next">
      <div class="container-fluid">
        

        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="section-title" data-aos="zoom-out">
              <h1>Whats Next</h1>
              <p></p>
            </div>
            <p class="next">
              We are looking forward to integrate our ml model with cctv cameras which are installed at public places 
              where in percentage of people not weraing mask in a particular area can be detected. We can also integrate it 
              in cameras placed outside shops and malls which have automatic gate opeining entry wherein people without Mask
              are not allowed to enter.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- ======= Team Section ======= -->
    <section id="team" class="team">
      <div class="container">

        <div class="section-title" data-aos="zoom-out">
          <h2>Team</h2>
          <p>Our Team</p>
        </div>

        <div class="row">

          <div class="col-lg-6 col-md-4 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up">
              <div class="member-img">
                <img src="" class="img-fluid" alt="">
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Aditya Jain</h4>
                <span>Full Stack Web Developer</span>
                <h3>19BIT0050</h3>
              </div>
            </div>
          </div>

          <div class="col-lg-6 col-md-4 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up">
              <div class="member-img">
                <img src="" class="img-fluid" alt="">
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Sayyam Maske</h4>
                <span>Full Stack Web Developer</span>
                <h3>19BIT0045</h3>
              </div>
            </div>
          </div>

          <div class="col-lg-6 col-md-4 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                <img src="" class="img-fluid" alt="">
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Naman Jain</h4>
                <span>ML</span>
                <h3>19BIT0002</h3>
              </div>
            </div>
          </div>

          <div class="col-lg-6 col-md-4 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                <img src="" class="img-fluid" alt="">
                <div class="social">
                  <a href="https://www.linkedin.com/in/aditya-jain-479b96157/"><i class="icofont-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Keshav Aggraval</h4>
                <span>ML</span>
                <h3>19BIT0009</h3>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>
    <!-- End Team Section -->


  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>Face Mask Detector</h3>
      <p>Detecting face masks, keeping people safe</p>
    
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>

  <!-- Vendor JS Files -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="vendor/php-email-form/validate.js"></script>
  <script src="vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="vendor/venobox/venobox.min.js"></script>
  <script src="vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="main.js"></script>

  <script>
    $(document).ready(function(){
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
    })
    
        function stop(){
            $("img").attr("src", "/static/images/stay-safe.jpg");
            $("#stop").attr("class","cta-btn align-middle");
    
            $("#start").attr("class","cta-btn align-middle");
        }
        function start(){
            $("img").attr("src", "{{url_for('main.video_feed')}}");
            $("#start").attr("class","cta-btn align-middle");
    
            $("#stop").attr("class","cta-btn align-middle");
        }
    
    </script>

</body>

</html>